/* Downloads the three brand families from Google Fonts as WOFF2 and writes
   public/fonts/ + src/styles/fonts.css. Space Grotesk and IBM Plex Sans are
   variable fonts — Google serves one file for every weight — so files are
   deduplicated by content hash and the @font-face rules share it. Without this
   the browser fetches the same bytes once per declared weight.
   Run: node scripts/fonts.mjs */
import { createHash } from 'node:crypto';
import { mkdirSync, writeFileSync, readdirSync, unlinkSync } from 'node:fs';
import { join } from 'node:path';

const FAMILIES = [
  { css: 'Space+Grotesk:wght@400;500;600;700', family: 'Space Grotesk', stem: 'spacegrotesk' },
  { css: 'IBM+Plex+Sans:wght@400;500;600', family: 'IBM Plex Sans', stem: 'plexsans' },
  { css: 'IBM+Plex+Mono:wght@400;500;600', family: 'IBM Plex Mono', stem: 'plexmono' },
];
const SUBSETS = ['latin', 'latin-ext'];
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36';
const OUT = 'public/fonts';

mkdirSync(OUT, { recursive: true });
for (const f of readdirSync(OUT)) unlinkSync(join(OUT, f));

const byContent = new Map();   // md5 -> filename
let css = '/* Generated by scripts/fonts.mjs — do not edit. Deduplicated: variable\n   families share one file across every declared weight. */\n';

for (const { css: spec, family, stem } of FAMILIES) {
  const res = await fetch(`https://fonts.googleapis.com/css2?family=${spec}&display=swap`, {
    headers: { 'User-Agent': UA },
  });
  const sheet = await res.text();

  for (const block of sheet.split('@font-face').slice(1)) {
    const url = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
    const weight = block.match(/font-weight:\s*(\d+)/)?.[1];
    const range = block.match(/unicode-range:\s*([^;]+);/)?.[1];
    if (!url || !weight || !range) continue;

    /* The subset name is the comment immediately preceding this block. */
    const before = sheet.slice(0, sheet.indexOf(url));
    const comments = [...before.matchAll(/\/\*\s*([a-z0-9-]+)\s*\*\//g)];
    const subset = comments.at(-1)?.[1] ?? 'latin';
    if (!SUBSETS.includes(subset)) continue;

    const bytes = Buffer.from(await (await fetch(url)).arrayBuffer());
    const digest = createHash('md5').update(bytes).digest('hex');

    let file = byContent.get(digest);
    if (!file) {
      file = `${stem}-${subset}-${digest.slice(0, 8)}.woff2`;
      writeFileSync(join(OUT, file), bytes);
      byContent.set(digest, file);
    }
    css += `@font-face{font-family:"${family}";font-style:normal;font-weight:${weight};font-display:swap;src:url("/fonts/${file}") format("woff2");unicode-range:${range};}\n`;
  }
}

writeFileSync('src/styles/fonts.css', css);
console.log(`${byContent.size} unique files, ${css.split('@font-face').length - 1} faces`);
