/* Downloads the brand families from Google Fonts as WOFF2 and writes
   public/fonts/, src/styles/fonts.css and src/styles/fonts.preload.json.

   Inter Tight (display) and Inter (text) are VARIABLE — Google serves one file
   for every weight — so files are deduplicated by content hash and the
   @font-face rules share it. JetBrains Mono carries labels and figures only,
   so it ships a single weight.

   latin-ext is deliberately not fetched: five files, 91 KB, never requested by
   any page, and ten more @font-face blocks in the render-blocking CSS. Add it
   back the day a post ships in Spanish — and re-measure.

   Run: node scripts/fonts.mjs */
import { createHash } from 'node:crypto';
import { mkdirSync, writeFileSync, readdirSync, unlinkSync } from 'node:fs';
import { join } from 'node:path';

const FAMILIES = [
  { css: 'Inter+Tight:wght@500;600;700;800', family: 'Inter Tight', stem: 'intertight' },
  { css: 'Inter:wght@400;500;600', family: 'Inter', stem: 'inter' },
  /* Labels and data only — one weight. */
  { css: 'JetBrains+Mono:wght@500', family: 'JetBrains Mono', stem: 'jbmono' },
];
const SUBSETS = ['latin'];
/* Faces needed to paint the first viewport. Preloaded from the layout, so they
   are not discovered two round trips deep behind the stylesheet. */
const PRELOAD = ['intertight', 'inter'];
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36';
const OUT = 'public/fonts';

mkdirSync(OUT, { recursive: true });
for (const f of readdirSync(OUT)) unlinkSync(join(OUT, f));

const byContent = new Map();   // md5 -> filename
const preload = [];
let css = '/* Generated by scripts/fonts.mjs — do not edit. Inter Tight and Inter are\n'
  + '   variable and share one file across every declared weight. */\n';

for (const { css: spec, family, stem } of FAMILIES) {
  const res = await fetch(`https://fonts.googleapis.com/css2?family=${spec}&display=swap`, {
    headers: { 'User-Agent': UA },
  });
  const sheet = await res.text();

  for (const block of sheet.split('@font-face').slice(1)) {
    const url = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
    const weight = block.match(/font-weight:\s*(\d+)/)?.[1];
    const range = block.match(/unicode-range:\s*([^;]+);/)?.[1];
    if (!url || !weight || !range) continue;

    /* The subset name is the comment immediately preceding this block. */
    const before = sheet.slice(0, sheet.indexOf(url));
    const comments = [...before.matchAll(/\/\*\s*([a-z0-9-]+)\s*\*\//g)];
    const subset = comments.at(-1)?.[1] ?? 'latin';
    if (!SUBSETS.includes(subset)) continue;

    const bytes = Buffer.from(await (await fetch(url)).arrayBuffer());
    const digest = createHash('md5').update(bytes).digest('hex');

    let file = byContent.get(digest);
    if (!file) {
      file = `${stem}-${subset}-${digest.slice(0, 8)}.woff2`;
      writeFileSync(join(OUT, file), bytes);
      byContent.set(digest, file);
      if (PRELOAD.includes(stem)) preload.push(`/fonts/${file}`);
    }
    css += `@font-face{font-family:"${family}";font-style:normal;font-weight:${weight};font-display:swap;src:url("/fonts/${file}") format("woff2");unicode-range:${range};}\n`;
  }
}

writeFileSync('src/styles/fonts.css', css);
/* Filenames are content-hashed, so the layout cannot hard-code them. */
writeFileSync('src/styles/fonts.preload.json', `${JSON.stringify(preload, null, 2)}\n`);
console.log(`${byContent.size} unique files, ${css.split('@font-face').length - 1} faces, ${preload.length} preloaded`);
