/* Every word that appears inside a clip. Examples are illustrative scenarios,
   not client data — names, amounts and documents are invented on purpose. */
export type Lang = "es" | "en";

export const S = {
  es: {
    voice: {
      incoming: "Llamada entrante",
      caller: "Cliente",
      assistant: "Asistente",
      q: "Hola, quería una habitación doble para este fin de semana.",
      a: "Perfecto. Tengo una doble del viernes 14 al domingo 16. ¿A nombre de quién la reservo?",
      done: "Reserva creada",
      rows: ["Habitación doble · 2 noches", "Vie 14 → Dom 16 · 2 huéspedes", "Confirmación enviada por SMS"],
      chips: ["Responde en < 2 s", "24/7", "ES · EN"],
    },
    docs: {
      inbox: ["Factura", "Nota de entrega", "Contrato"],
      reading: "Leyendo documento",
      title: "Datos extraídos",
      fields: [
        ["Tipo", "Nota de entrega"],
        ["Proveedor", "Cementos del Norte, S.A."],
        ["Fecha", "03/10/2026"],
        ["Obra", "Residencial Las Palmas · B"],
        ["Importe", "US$ 4.820,00"],
      ],
      saved: "Validado y archivado",
      review: "1 dato dudoso → revisión humana",
    },
    billing: {
      inbox: "Facturas recibidas",
      month: "este mes",
      suppliers: [
        ["Ferretería Central", "1.180,00"],
        ["Electricidad Ruiz", "642,50"],
        ["Transportes Mar", "2.360,00"],
      ],
      entry: "Asiento contable",
      cols: ["Cuenta", "Debe", "Haber"],
      lines: [
        ["Compras", "1.000,00", ""],
        ["Impuesto soportado", "180,00", ""],
        ["Proveedores", "", "1.180,00"],
      ],
      balanced: "Cuadrado",
      exported: "Exportado a tu programa contable",
    },
    assistant: {
      sources: "Documentos de la empresa",
      docs: ["Manual de operaciones", "Política de eventos", "Contratos de proveedores", "Procedimientos de obra"],
      q: "¿Con cuánta antelación puede cancelar un grupo de más de 20 personas?",
      a: "Hasta 30 días antes de la llegada sin coste. Después se factura el 50 % de la primera noche.",
      cite: "Política de eventos · pág. 12",
    },
    custom: {
      need: "Lo que necesitas",
      brief: "Un portal para que nuestros clientes vean el avance de cada obra, con fotos y alertas.",
      building: "Lo construimos",
      blocks: ["Web y app", "API", "Datos", "IA", "Nube"],
      app: "Portal de obras",
      projects: [["Residencial Las Palmas", 72], ["Hotel Costa Norte", 45], ["Naves Industriales", 88]],
      alert: "Retraso detectado · Bloque B",
      sent: "Aviso enviado al cliente",
    },
    infra: {
      stages: ["Código", "Pruebas", "Build", "Despliegue"],
      cloud: "Tu nube",
      envs: ["Producción", "Pruebas"],
      deployLabel: "Tiempo de despliegue",
      before: "1 semana",
      after: "1 hora",
      chips: ["Infraestructura como código", "Copias y alertas", "Coste vigilado"],
    },
  },
  en: {
    voice: {
      incoming: "Incoming call",
      caller: "Guest",
      assistant: "Assistant",
      q: "Hi, I'd like a double room for this weekend.",
      a: "Sure. I have a double from Friday the 14th to Sunday the 16th. What name should I put it under?",
      done: "Booking created",
      rows: ["Double room · 2 nights", "Fri 14 → Sun 16 · 2 guests", "Confirmation sent by SMS"],
      chips: ["Replies in < 2 s", "24/7", "EN · ES"],
    },
    docs: {
      inbox: ["Invoice", "Delivery note", "Contract"],
      reading: "Reading document",
      title: "Extracted data",
      fields: [
        ["Type", "Delivery note"],
        ["Supplier", "Northern Cement Ltd."],
        ["Date", "2026-10-03"],
        ["Site", "Las Palmas Residential · B"],
        ["Amount", "US$ 4,820.00"],
      ],
      saved: "Checked and filed",
      review: "1 uncertain field → human review",
    },
    billing: {
      inbox: "Invoices received",
      month: "this month",
      suppliers: [
        ["Central Hardware", "1,180.00"],
        ["Ruiz Electrical", "642.50"],
        ["Mar Logistics", "2,360.00"],
      ],
      entry: "Journal entry",
      cols: ["Account", "Debit", "Credit"],
      lines: [
        ["Purchases", "1,000.00", ""],
        ["Input tax", "180.00", ""],
        ["Suppliers", "", "1,180.00"],
      ],
      balanced: "Balanced",
      exported: "Exported to your accounting software",
    },
    assistant: {
      sources: "Company documents",
      docs: ["Operations manual", "Events policy", "Supplier contracts", "Site procedures"],
      q: "How far ahead can a group of more than 20 people cancel?",
      a: "Up to 30 days before arrival at no cost. After that, 50% of the first night is charged.",
      cite: "Events policy · p. 12",
    },
    custom: {
      need: "What you need",
      brief: "A portal where our clients can follow each site's progress, with photos and alerts.",
      building: "We build it",
      blocks: ["Web & app", "API", "Data", "AI", "Cloud"],
      app: "Site portal",
      projects: [["Las Palmas Residential", 72], ["Costa Norte Hotel", 45], ["Industrial Units", 88]],
      alert: "Delay detected · Block B",
      sent: "Client notified",
    },
    infra: {
      stages: ["Code", "Tests", "Build", "Deploy"],
      cloud: "Your cloud",
      envs: ["Production", "Staging"],
      deployLabel: "Time to deploy",
      before: "1 week",
      after: "1 hour",
      chips: ["Infrastructure as code", "Backups & alerts", "Cost kept in check"],
    },
  },
} as const;
